services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./task-backend
    container_name: task_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: task_db

  frontend:
    build: ./task-frontend
    container_name: task_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: