version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./task-backend
    container_name: task_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./task-backend/.env.docker

  frontend:
    build: ./task-frontend
    container_name: task_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: