name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend deps
        run: cd task-frontend && npm install

      - name: Build frontend
        run: cd task-frontend && npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend deps
        run: cd task-backend && npm install